### PR TITLE
Converted all POSTable PHP files to use the admin-post.php functions

### PR DESCRIPTION
**Pull request by cmowenby**
Secured our POSTs behind Wordpress in order to protect unauthorized posting and have people directly access POSTable PHP files. 

There is a new folder called "postable". 

In this folder is all of the PHP functions that are hooked into the Wordpress admin post functions. All of the other postable PHP files have been removed in order to prevent the continued use of this security hole.

Additionally, due to the commit-heavy bugfixing section of this branch, I recommend a squash merge to the final reviewer.

### CODE REVIEW

**Comment by thomascoe** [comment]
Code itself looks good, going to load it on the website and run through some manual tests to be sure everything seems to still work before approving

**Comment by thomascoe** [comment]
Updating G Suite key doesn't work

**Comment by thomascoe** [comment]
Registration page also doesn't work. Browser goes to https://goatr.tech/wp-admin/admin-post.php which just shows a blank page

**Comment by thomascoe** [comment]
To elaborate on my last comment, registration form works until the last step. Once entering payment, submitting that information goes to the page described. Doesn't seem to create the user in Stripe so I assume the registration process fails entirely

**Comment by thomascoe** [comment]
I fixed the G Suite Key form so that it calls the correct admin function, so it updates the G Suite key now but now it messes up the key when it saves. Each time you save it seems to introduce new backslashes into the keys. @cmowenby please look at this

**Comment by thomascoe** [comment]
I didn't do anything to fix the registration form yet, but I'm not convinced that the user registration form needs to be secured behind the wordpress admin side anyway since it should be able to be called by the public. We already prevent manual POST's to the form through Stripe. You need a valid one-time-use Stripe token to create a customer in the registration process, which is generated in the previous step. I don't see any benefit to moving the last step of registraiton to this postable directory behind admin post. Unless I'm proven otherwise, my vote is that the registration form should be reverted to how it is currently set up in master.

**Comment by thomascoe** [comment]
The registration page could also have "defined( 'ABSPATH' ) or die();" added to the version in master now. That would additionally prevent manual posts to the form (which would already fail anyway because they wouldn't have a valid Stripe token). Although even if someone even could manually post to submit.php with a valid stripe token, there's nothing nefarious they could do. All of the subscription stuff and prices are generated programmatically from Stripe and couldn't be modified.

**Comment by thomascoe** [comment]
Okay I must be missing this, but I'm actually failing to see how using admin-post.php in any of these cases provides additional security than simply using "defined( 'ABSPATH' ) or die();" at the top of the page.

Can someone explain to me what specifically the security issue is that admin-post.php solves? Everything I've found online seems to suggest that admin-post.php isn't intended to provide security and using it can complicate design in the long run (e.g. requiring a redirect to return users to the UI, requiring additional hooks for the plugin).

**Comment by cmowenby** [comment]
Since I can't reply directly to each comment, I'll try to address everything in this one @thomascoe .

The escape characters have been removed from the GSuite API key.

For the registration page "not functioning", there is no hook for when you're logged in, because you in theory would not be registering a new user if you're currently logged in. That can be changed easily, but that's a design decision we will have to make, and one way or the other, we should have a UI that alerts the user accordingly.

The idea behind using admin-post.php for the administrator functions is to prevent unauthenticated actions and posts from occurring.

The main reason why the Registration page was changed to use the WP POST handling was to keep consistency in design. I'd like to hear how @ryanstrat feels about it.

As for the registration page, there is an MITM attack that could be easily done once we have the password hash being passed during registration. After the user has entered the stripe payment information, an adversary could, in theory, intercept that post, replace the password hash with their own, and then have access to the GSuite account. This would require a vulnerability in TLS, but it's still something I think we should address. That could be done without the Wordpress intervention however.

**Comment by thomascoe** [comment]
Thanks for fixing the G Suite thing!

I see the issue for the registration page, I didn't think about how I was logged in. Yeah there was no error for that so I didn't know what the issue was. We should definitely have some sort of error shown regardless of how we decide to implement it.

I see now why we used admin-post.php for the pages which just posted the data to a raw PHP file that wasn't loaded within wordpress. I think that's an acceptable solution for pages like the integrations update page and the admin user card update page where it just processes the input and redirects to another page.

For something like registration, I think our existing solution in master is a better design because of the way those PHP files are loaded within wordpress from the header. Maybe @ryanstrat can weigh in on his thoughts here too, but my opinion is that the existing design was an elegant way to handle all of the registration PHP: since they were all loaded through wordpress we can easily add the ABSPATH check to prevent manual POSTing (which isn't a security concern here anyway because of the one time nature of the Stripe tokens), plus the existing design makes it easier to build off of and implement a progress bar across the top of the registration page like we had discussed before. Since the existing design is easier to build off of and is just as secure in this case, my vote is not changing it.

As to your final point about the MITM attack, I don't think using admin-post.php mitigates that. If someone has broken TLS and has MITM'd users connecting to the server, the attacker could have full control regardless.

**Comment by ryanstrat** [comment]
If the admin-post.php system is authenticating users before accepting a post, how would it work for the registration page, where users are not signed in? And if it does work, then how is it providing additional security to the other pages?

I'm not concerned about a MITM attack. We can assume that TLS is not broken. We could add HSTS to our server if we are really concerned.

**Comment by thomascoe** [comment]
@ryanstrat there is an option for admin-post.php to allow unauthenticated POSTs, which is what Craig is using. For the other pages, he only allows authenticated POSTs. For the registration form, admin-post.php doesn't provide any additional security.

I reviewed the functionality behind the latest commits and I'm satisfied that the code in this branch works for updating API keys and for the registration process. We just need to decide whether to use admin-post.php in the registration process or not.

Another concern I just thought about with having the registration form use admin-post.php is the fact that we have to do a redirect somewhere at the end of the function, so we can't return any data to the user if we ever wanted to display something other than a generic "success" or "failure" message.  Basically while using admin-post.php does functionally work for the registration page, I'm concerned using it here may put us into a box and limit future changes that we (or a future maintainer) may want to make to the registration process.

**Comment by ryanstrat** [comment]
I don't think consistency is a strong enough argument to reduce functionality. Passing back more specific error messages could be helpful in the future, but I don't think it is critical functionality.

Could we include a url parameter with the redirect url to pass an error message back? Ultimately, I don't see a strong argument for either way.

**Comment by thomascoe** [comment]
I suppose we could include a GET parameter in the redirect url to pass messages back, but that seems a little hacky

**Comment by ryanstrat** [comment]
Given the marginal benefits, have we dicussed which method will require more work to complete?

**Comment by thomascoe** [comment]
We've already completed both. Craig has the admin-post.php method in this branch, and the other implementation is in master.

**Comment by ryanstrat** [comment]
I know that both of you have worked hard on this, but I don't think it matters which we pick.

**Comment by ryanstrat** [comment]
I think I'm in favor of consistency, though

**Comment by thomascoe** [comment]
Consistency with what? The implementation in master is consistent with the rest of the registration process and with the other admin pages, the implementation in this branch is consistent with the other pages that use admin-post.php

**Comment by ryanstrat** [comment]
Keeping all REST posts consistent with using the admin-post.php methodology.

**Comment by thomascoe** [comment]
The previous step of the registration process sends a POST without going through the admin-post.php methodology. Should that be changed as well? Changing the final step introduces inconsistency with the POSTs in the registration process

**Comment by ryanstrat** [comment]
So then picking admin-post would require further work to complete, which puts me in favor of leaving registration as-is

**Review by thomascoe — APPROVED** [review]
Code looks good. Tested the registration process and it seems to work as well. I approve.

**Pull request merged**
