### PR TITLE
Cleaning up unused WP Plugin boilerplate functions

### PR DESCRIPTION
**Pull request by cmowenby**
Removed instances of "Plugin Name" throughout the plugin. Removed unused WP plugin boilerplate functions as well as the admin and public files, as our plugin handles that. 

This already includes the updated security fixes branch, so please accept that PR before accepting this one.

### CODE REVIEW

**Comment by thomascoe** [comment]
Before I review, Craig can you please pull in master and fix the merge conflicts?

**Comment by thomascoe** [comment]
Skimming the code looks fine. I want to test taking a .zip of our plugin and importing it into wordpress to be sure that works properly though. But I don't want to mess up the git stuff on the server. Is there a way we can test this?

**Review by ryanstrat — APPROVED** [review]
Looks good to me. Once it is tested, as Thomas requested, go ahead and merge.

**Comment by thomascoe** [comment]
Whoever merges, please squash and merge! There's a ton of commits in this one

**Comment by cmowenby** [comment]
I uploaded the zip file from the repo, it worked minus the fact that vendor autoload PHP files don't exist. All in all, I believe that it'll function properly.

**Pull request merged**
