### PR TITLE
Send Slack invites on registration

### PR DESCRIPTION
**Pull request by ryanstrat**
Includes all of the changes from the bug fix PR as well.

This PR is specifically to implement #69.

### CODE REVIEW

**Comment by thomascoe** [comment]
This is something I found in an article about securing Wordpress Plugins:
image

I think we should look into using these wordpress functions instead of CURL if possible

**Comment by cmowenby** [comment]
I have updated it work via the wp_remote_get function for security. Tested and it functioned properly.

**Review by thomascoe — APPROVED** [review]
Looks good to me

**Review by ryanstrat — COMMENTED** [review]
Looks good, I can't approve, since it's my PR

**Pull request merged**
