### PR TITLE
UI -- contains bootstrapped pages and new member view view 

### PR DESCRIPTION
**Pull request by jmbrown864**

### CODE REVIEW

**Comment by thomascoe** [comment]
Admin-integrations page was broken because it was reverted back to old POST method instead of admin-post.php. I just fixed that

**Comment by thomascoe** [comment]
Okay I did some work to remove the extra `<html>` `<head>` and `<body>` tags from the member page since those are already generated by Wordpress by the header and footer. The one issue is I can't remove this extra `<body>` tag without it messing up the page real bad:

image

Is there a way to add the ng-app and ng-controller things to the page without putting them in the `<body>` tag, since I don't think we have control over that?

**Comment by thomascoe** [comment]
Also, I'm fairly certain that all the php at the top of member-page.html is still being executed since it's only commented out in HTML and not in PHP, which is incredibly misleading functionality. Can this php be fully removed?

I'll approve once this extra PHP is either removed or un-commented (since it's still being executed even while commented out), and we've found a solution to being able to remove the extra `<body>` tag without messing up the page

**Comment by thomascoe** [comment]
Okay the extra `<body>` tag is resolved. We just need to figure out the issues with loading the styles and scripts (like with the wp_enqueue_x functions). Maybe there's a way we could have our plugin hook into something and load bootstrap/angular on all of our pages?

**Comment by thomascoe** [comment]
I added some more commits here to update the member page UI to have the card update stuff, and to update the admin user edit UI to not have it anymore.

Can we approve this as-is because there are so many changes since everything works now? And then make another PR later to load the angular scripts in the more wordpress-y way

**Review by danaalyse — APPROVED** [review]
Functionality is fine
We just need to make sure we call the scripts correctly.

**Pull request merged**
