### PR TITLE
Made administrator email alerts configurable to an arbitrary number of email addresses.

### PR DESCRIPTION
**Pull request by cmowenby**
See title.

### CODE REVIEW

**Comment by thomascoe** [comment]
Looks good! Can you also implement this change in resources/stripehook.php too though for the wp_mail call it makes?

**Comment by cmowenby** [comment]
Stripe webhook section has been added :+1:

**Comment by thomascoe** [comment]
Approved

**Review by jmbrown864 — APPROVED** [review]

**Comment by thomascoe** [comment]
Also note for tracking, this fixes issue #92

**Review by ryanstrat — APPROVED** [review]
lgtm

**Pull request merged**
