### PR TITLE
Add RFID Tag # to User Table

### PR DESCRIPTION
**Pull request by thomascoe**
Fix issue #76 
Also adds backend functions for getting and setting RFID tag

### CODE REVIEW

**Review by cmowenby — APPROVED** [review]
Code looks great, and it appears to be function on the dev site. Great work!

**Review by cmowenby — DISMISSED** [review]
I apologize for that mixup. Currently, the RFID tag branch loads the admin page in about 30s. Is there any way to speed this up?

**Comment by ryanstrat** [comment]
It might be worthwhile to reduce the number of queries we're making by combining certain calls.

**Comment by thomascoe** [comment]
I agree that the current load time is unacceptable. I'll look at optimizing this

**Comment by thomascoe** [comment]
@cmowenby My latest commit reduces load times of the html for the user table down to ~0.5 sec from ~12 sec. This should resolve your issue. Let me know if anything else needs fixing

**Comment by jmbrown864** [comment]
Approved

**Comment by jmbrown864** [comment]
Approve!

**Comment by ryanstrat** [comment]
Looks good to me

**Review by ryanstrat — APPROVED** [review]
Approved

**Pull request merged**
